# Python Basics 9: Numpy Arrays and Linear Algebra

The ability to do basic things with numerical arrays (vectors and matrices) is extremely important in data science applications.
We do numerical algebra in Python using the [Numpy](https://numpy.org/).
Numpy is a **huge** Python library and it has a lot of details.
We are going to cover the very basics here.
When there is something specific that you want to do, the best way to figure out how to do it is to Google it.

First, let's import ``numpy``.
We typically, do it by creating a shortcut called ``np``:

In [1]:
import numpy as np

In this way you can access whatever is in ``numpy`` by going throuh ``np`` which is less characters.
Let's create a 1D numpy array from a list:

In [2]:
a = np.array([1.2, 2.0, 3.0, -1.0, 2.0])
print(a)

[ 1.2  2.   3.  -1.   2. ]


This behaves just like a vector in Matlab.
You can multiply with a number:

In [3]:
2.0 * a

array([ 2.4,  4. ,  6. , -2. ,  4. ])

In [4]:
a * 3

array([ 3.6,  6. ,  9. , -3. ,  6. ])

You can add another vector (of the same size):

In [5]:
b = np.array([1, 2, 3, 4, 5])
c = a + b
c

array([2.2, 4. , 6. , 3. , 7. ])

You can raise all elements to a power:

In [6]:
a ** 3

array([ 1.728,  8.   , 27.   , -1.   ,  8.   ])

Or you can apply a standard function to all elements:

In [7]:
np.exp(a)

array([ 3.32011692,  7.3890561 , 20.08553692,  0.36787944,  7.3890561 ])

In [8]:
np.cos(a)

array([ 0.36235775, -0.41614684, -0.9899925 ,  0.54030231, -0.41614684])

In [9]:
np.sin(a)

array([ 0.93203909,  0.90929743,  0.14112001, -0.84147098,  0.90929743])

In [10]:
np.tan(a)

array([ 2.57215162, -2.18503986, -0.14254654, -1.55740772, -2.18503986])

Notice that the functions you can use are in ``np``.
Here is how you can get how many elements you have in the array:

In [11]:
a.shape

(5,)

Also, to see if this is a 1D array (higher dimensional arrays, 2D, 3D, etc. are also possible), you can use this:

In [12]:
a.ndim

1

You access the elements of the array just like the elements of a list:

In [13]:
a[0]

np.float64(1.2)

In [14]:
a[1]

np.float64(2.0)

In [15]:
a[2:4]

array([ 3., -1.])

In [16]:
a[::2]

array([1.2, 3. , 2. ])

In [17]:
a[::-1]

array([ 2. , -1. ,  3. ,  2. ,  1.2])

You can find the minimum or the maximum of the array like this:

In [18]:
a.min()

np.float64(-1.0)

In [19]:
a.max()

np.float64(3.0)

So, notice that ``a`` is an object of a class.
The class is called ``np.ndarray``:

In [20]:
type(a)

numpy.ndarray

and ``min()`` and ``max()`` are functions of the ``np.ndarray`` class.
Another function of the class is the dot product:

In [21]:
a.dot(b)

np.float64(20.2)

There is also a submodule called ``numpy.linalg`` which has some linear algebra functions you can apply to arrays.
For 1D arrays (aka vectors) the vector norm is a useful one:

In [22]:
np.linalg.norm(a)

np.float64(4.409081537009721)

In [23]:
help(np.linalg.norm)

Help on _ArrayFunctionDispatcher in module numpy.linalg:

norm(x, ord=None, axis=None, keepdims=False)
    Matrix or vector norm.
    
    This function is able to return one of eight different matrix norms,
    or one of an infinite number of vector norms (described below), depending
    on the value of the ``ord`` parameter.
    
    Parameters
    ----------
    x : array_like
        Input array.  If `axis` is None, `x` must be 1-D or 2-D, unless `ord`
        is None. If both `axis` and `ord` are None, the 2-norm of
        ``x.ravel`` will be returned.
    ord : {int, float, inf, -inf, 'fro', 'nuc'}, optional
        Order of the norm (see table under ``Notes`` for what values are
        supported for matrices and vectors respectively). inf means numpy's
        `inf` object. The default is None.
    axis : {None, int, 2-tuple of ints}, optional.
        If `axis` is an integer, it specifies the axis of `x` along which to
        compute the vector norms.  If `axis` is a 2-tuple

## Questions
Consider the two vectors:

In [24]:
r1 = np.array([1.0, -2.0, 3.0])
r2 = np.array([2.0, 2.0, -3.0])

Use numpy functionality to:
+ Find a unit vector in the direction of ``r1``:

In [27]:
# Your code here
r1_unit_vector = r1/np.linalg.norm(r1)
r1_unit_vector

array([ 0.26726124, -0.53452248,  0.80178373])

+ Find the angle between ``r1`` and ``r2`` in radians:

In [30]:
# Your code here
r1_r2_angle = np.acos(np.linalg.vecdot(r1,r2)/(np.linalg.norm(r1)* np.linalg.norm(r2)))
r1_r2_angle

np.float64(2.36459824719772)

+ The projection of ``r2`` on ``r1``:

In [ ]:
# Your code here
r2_project_r1 = np.linalg.vecdot(r2, r1)/np.linalg.norm(r1)

+ Use [numpy.cross](https://numpy.org/doc/stable/reference/generated/numpy.cross.html) to find the cross product between ``r2`` and ``r1``. Then, verify numerically (using numpy functionality) that $\vec{r}_1\cdot\left(\vec{r}_1\times\vec{r}_2\right) = 0$.

In [32]:
# Your code here
r1_cross_r2 = np.cross(r1, r2)
dot_cross = np.dot(r1, r1_cross_r2)
dot_cross

np.float64(0.0)

## Matrices

Now, let's go to two dimensional arrays.
Of course, you can think of the vectors as two dimensional arrays.
In particular, you can think of them as a matrix with a single column.
To do this in numpy you need to reshape the vectors:

In [33]:
# The original vector
a

array([ 1.2,  2. ,  3. , -1. ,  2. ])

In [34]:
# The vector as a single column matrix
acm = a.reshape((5, 1))
acm

array([[ 1.2],
       [ 2. ],
       [ 3. ],
       [-1. ],
       [ 2. ]])

In [35]:
# There is one more way you can achieve the same thing
# (and I am going to be using it because it requires less typing)
acm = a[:, None]
acm

array([[ 1.2],
       [ 2. ],
       [ 3. ],
       [-1. ],
       [ 2. ]])

The code ``a[:, None]`` means "pretend that the array has one more index that is always zero."

Now, since ``acm`` is a 2D array:

In [36]:
acm.ndim

2

Look also at the shape:

In [37]:
acm.shape

(5, 1)

So, the shape is (5, 1). This means that there are 5 rows and one colum.
You can access elements in this 2D array with indices like this:

In [38]:
acm[0, 0]

np.float64(1.2)

In [39]:
acm[1, 0]

np.float64(2.0)

And so on. Of course, the second index can only be zero because you only have one column.

Let's now make a 2D matrix to play with:

In [40]:
A = np.array(
    [
        [2.0, -1.0, 0.0, 0.0, 0.0],
        [-1.0, 2.0, -1.0, 0.0, 0.0],
        [0.0, -1.0, 2.0, -1.0, 0.0],
        [0.0, 0.0, -1.0, 2.0, -1.0],
        [0.0, 0.0, 0.0, -1.0, 2.0]
    ]
)
A

array([[ 2., -1.,  0.,  0.,  0.],
       [-1.,  2., -1.,  0.,  0.],
       [ 0., -1.,  2., -1.,  0.],
       [ 0.,  0., -1.,  2., -1.],
       [ 0.,  0.,  0., -1.,  2.]])

Notice that we used an list of rows and each row was a list of numbers.
Here are the dimensions of ``A``:

In [41]:
A.ndim

2

In [42]:
A.shape

(5, 5)

Let's access some elements of ``A``:

In [43]:
A[0, 0]

np.float64(2.0)

In [44]:
A[2, 2]

np.float64(2.0)

You can access the 3rd row like this:

In [45]:
A[2]

array([ 0., -1.,  2., -1.,  0.])

You can get a submatrix, say the first 3x3 submatrix like this:

In [46]:
A[:3, :3]

array([[ 2., -1.,  0.],
       [-1.,  2., -1.],
       [ 0., -1.,  2.]])

And so on.

You can multiply matrices with numbers:

In [47]:
2.0 * A

array([[ 4., -2.,  0.,  0.,  0.],
       [-2.,  4., -2.,  0.,  0.],
       [ 0., -2.,  4., -2.,  0.],
       [ 0.,  0., -2.,  4., -2.],
       [ 0.,  0.,  0., -2.,  4.]])

In [48]:
A * 3.0

array([[ 6., -3.,  0.,  0.,  0.],
       [-3.,  6., -3.,  0.,  0.],
       [ 0., -3.,  6., -3.,  0.],
       [ 0.,  0., -3.,  6., -3.],
       [ 0.,  0.,  0., -3.,  6.]])

You can raise them to a power:

In [49]:
A ** 3

array([[ 8., -1.,  0.,  0.,  0.],
       [-1.,  8., -1.,  0.,  0.],
       [ 0., -1.,  8., -1.,  0.],
       [ 0.,  0., -1.,  8., -1.],
       [ 0.,  0.,  0., -1.,  8.]])

You can pass them through functions:

In [50]:
np.exp(A)

array([[7.3890561 , 0.36787944, 1.        , 1.        , 1.        ],
       [0.36787944, 7.3890561 , 0.36787944, 1.        , 1.        ],
       [1.        , 0.36787944, 7.3890561 , 0.36787944, 1.        ],
       [1.        , 1.        , 0.36787944, 7.3890561 , 0.36787944],
       [1.        , 1.        , 1.        , 0.36787944, 7.3890561 ]])

You can add them together:

In [51]:
A + A

array([[ 4., -2.,  0.,  0.,  0.],
       [-2.,  4., -2.,  0.,  0.],
       [ 0., -2.,  4., -2.,  0.],
       [ 0.,  0., -2.,  4., -2.],
       [ 0.,  0.,  0., -2.,  4.]])

You can multiply them together (assuming that the dimensions match):

In [52]:
A.dot(A)

array([[ 5., -4.,  1.,  0.,  0.],
       [-4.,  6., -4.,  1.,  0.],
       [ 1., -4.,  6., -4.,  1.],
       [ 0.,  1., -4.,  6., -4.],
       [ 0.,  0.,  1., -4.,  5.]])

You can multiply a matrix with a vector:

In [53]:
A.dot(a)

array([ 0.4, -0.2,  5. , -7. ,  5. ])

Remember the column matrix ``acm``:

In [54]:
acm

array([[ 1.2],
       [ 2. ],
       [ 3. ],
       [-1. ],
       [ 2. ]])

You can also multiply the matrix with it since the dimensions match:

In [55]:
A.dot(acm)

array([[ 0.4],
       [-0.2],
       [ 5. ],
       [-7. ],
       [ 5. ]])

You can also multiply ``acm`` (5x1) with its transpose (1x5).
The transpose is:

In [56]:
acm.T

array([[ 1.2,  2. ,  3. , -1. ,  2. ]])

And here is the result of the multiplication:

In [57]:
acm.dot(acm.T)

array([[ 1.44,  2.4 ,  3.6 , -1.2 ,  2.4 ],
       [ 2.4 ,  4.  ,  6.  , -2.  ,  4.  ],
       [ 3.6 ,  6.  ,  9.  , -3.  ,  6.  ],
       [-1.2 , -2.  , -3.  ,  1.  , -2.  ],
       [ 2.4 ,  4.  ,  6.  , -2.  ,  4.  ]])

Here is another example of the transpose operator:

In [58]:
B = np.arange(25).reshape(5, 5)
B

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [59]:
B.T

array([[ 0,  5, 10, 15, 20],
       [ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24]])

There are some special numpy functions for creating arrays.
Here is how to make an array of zeros:

In [60]:
np.zeros((4, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

An array of ones:

In [61]:
np.ones((5, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

A unit matrix:

In [62]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Now, we typically want to do some more linear algebra with matrices.
For example, we may want to get the determinant of a matrix:

In [63]:
np.linalg.det(A)

np.float64(6.0)

Or we may want to solve a linear system of the form:
$$
A x = b,
$$
where $b$ is a given vector and $x$ is the uknown vector we are looking for.
Let's create and solve such a linear system.

In [ ]:
# I already have 5x5 matrix A, just define the b:
b = np.array([2.0, -1.0, 3.0, 4.0, 2.0])

In [64]:
# Here is how to solve the linear system:
x = np.linalg.solve(A, b)
x

array([ 5.83333333, 10.66666667, 13.5       , 13.33333333,  9.16666667])

Let's see if the solution works as expected by calculating $Ax$:

In [65]:
print("Ax = ", A.dot(x))
print("b  = ", b)

Ax =  [1. 2. 3. 4. 5.]
b  =  [1 2 3 4 5]


You can also find the eigenvalues of a matrix:

In [66]:
lam, v = np.linalg.eig(A)

The eigenvalues are:

In [67]:
lam

array([3.73205081, 3.        , 2.        , 0.26794919, 1.        ])

The eigenvectors are put in a matrix:

In [68]:
v

array([[ 2.88675135e-01,  5.00000000e-01,  5.77350269e-01,
         2.88675135e-01, -5.00000000e-01],
       [-5.00000000e-01, -5.00000000e-01, -1.22011980e-16,
         5.00000000e-01, -5.00000000e-01],
       [ 5.77350269e-01,  6.39436936e-16, -5.77350269e-01,
         5.77350269e-01, -3.68521763e-16],
       [-5.00000000e-01,  5.00000000e-01,  2.09033864e-16,
         5.00000000e-01,  5.00000000e-01],
       [ 2.88675135e-01, -5.00000000e-01,  5.77350269e-01,
         2.88675135e-01,  5.00000000e-01]])

So, each column of that matrix is an eigenvector.
Let's test that 
$$
A v_i = \lambda_i v_i,
$$
for the $i$-th eigenvalue:

In [69]:
# Which eigenvalue do you want to test:
i = 0
print("Av_i        = ", A.dot(v[:, i]))
print("lamda_i v_i = ", lam[i] * v[:, i])

Av_i        =  [ 1.07735027 -1.8660254   2.15470054 -1.8660254   1.07735027]
lamda_i v_i =  [ 1.07735027 -1.8660254   2.15470054 -1.8660254   1.07735027]


By the way, ``v[:, i]`` gives you the $i$-th column of the matrix ``v``.

### Questions

+ Consider the quadratic function:
$$
f(x_1, x_2) = x_1^2 -x_1x_2 + x_2^2 + 3x_1 + 4x_2.
$$
We are interested in finding its minimum.
A necessary condition for the minimum is that the gradient of $f(x_1, x_2)$ is zero.
The gradient is:
$$
\frac{\partial f(x_1,x_2)}{\partial x_1} = 2x_1 -x_2 + 3 = 0,
$$
and
$$
\frac{\partial f(x_1, x_2)}{\partial x_2} = -x_1 + 2x_2 + 4 = 0.
$$
Rearranging, we get the two equations:
$$
\begin{array}{ccc}
2x_1 - x_2 &=& -3,\\
-x_1 + 2x_2 &=& -4.\\
\end{array}
$$
These can also be written in matrix-vector form:
$$
\begin{bmatrix}
2 &-1\\
-1 & 2
\end{bmatrix}\cdot
\begin{bmatrix}
x_1\\
x_2
\end{bmatrix}
= \begin{bmatrix}
-3\\
-4
\end{bmatrix}.
$$
Use the numpy functionality to solve this linear system and thus find the minimum of $f(x_1,x_2)$.

In [77]:
# your code here
A = np.array([[2, -1], [-1, 2]])
b = np.array([-3,-4])
x = np.linalg.solve(A, b)
x

array([-3.33333333, -3.66666667])

+ For the point you found above to be a true minimum of the $f(x_1,x_2)$ (and not a maximum for example) is that the matrix of second derivatives (the so-called Hessian matrix) must be positive definite, i.e., that the matrix has only positive eigenvalues.
The hessian matrix in this problem is:
$$
H = \begin{bmatrix}
\frac{\partial^2 f(x_1,x_2)}{\partial x_1^2}& \frac{\partial^2 f(x_1,x_2)}{\partial x_1\partial x_2}\\
\frac{\partial^2 f(x_1,x_2)}{\partial x_1\partial x_2} & \frac{\partial^2 f(x_1,x_2)}{\partial x_1^2}
\end{bmatrix} =
\begin{bmatrix}
2 &-1\\
-1 & 2
\end{bmatrix}.
$$
Use numpy functionality to verify that the matrix $H$ is indeed positive definite.

In [87]:
# your code here
H = np.array([[2, -1], [-1, 2]])
H.shape
x.shape

(2,)

+ If $H$ is a positive definite matrix, then the following property is true for any vector $x\not = 0$:
$$
x^THx \ge 0.
$$
In words, if you sandwich $H$ around the same vector produce a scalar, that scalar is a positive number.
Test this hypothesis numerically using numpy functioanlity.
Hint: Use the ``dot`` function and twich to calculate $x^THx$.

In [89]:
# here is a random vector for you to play with:
x = np.random.randn(2)
print(f"x = {x}")
# Your code here: Compute x^T * H * x:
val = np.dot(x.transpose(), H.dot(x))
val

x = [-0.69404461  0.36412481]


np.float64(1.7340073191812042)

## Multi-dimensional numpy arrays

You can have 3D numpy arrays:

In [90]:
C = np.random.randn(10, 3, 4)
C

array([[[-0.99904027,  1.94097066,  0.84166429, -1.1504972 ],
        [-2.01249724, -0.65134131, -0.60816786,  0.0099742 ],
        [ 1.0128213 , -1.35478785,  0.47026273,  0.69301059]],

       [[ 0.77647479, -0.31413568,  0.56824339, -0.52720402],
        [-1.0523477 ,  0.6820921 ,  1.24112387,  0.73977306],
        [-1.18510041, -1.4853185 , -1.29936706,  0.22391172]],

       [[-0.64499449, -0.80057404, -0.25193021, -0.79068985],
        [ 0.72740508,  1.27724447,  0.43048132,  1.69649485],
        [-1.39201167, -0.30798603,  0.33407345,  0.92257025]],

       [[-0.68467973,  1.06419904, -1.17180509,  0.77469043],
        [ 1.77750196,  0.24348246,  1.21092068, -1.15208142],
        [-0.31331922,  0.35276078,  0.79487735, -0.13892828]],

       [[-1.42844806,  1.39270646, -1.79882322, -0.28801749],
        [ 1.27581327, -1.12124111,  1.29796926,  0.45089301],
        [-0.08118659, -1.02496587,  0.12103394, -0.01160108]],

       [[-1.90530907, -0.49146159, -0.22005646,  1.84106427]

In [91]:
C.ndim

3

In [92]:
C.shape

(10, 3, 4)

In [93]:
C[0, 2, 3]

np.float64(0.6930105852612695)

In [94]:
C[0]

array([[-0.99904027,  1.94097066,  0.84166429, -1.1504972 ],
       [-2.01249724, -0.65134131, -0.60816786,  0.0099742 ],
       [ 1.0128213 , -1.35478785,  0.47026273,  0.69301059]])

In [95]:
C[0, 1]

array([-2.01249724, -0.65134131, -0.60816786,  0.0099742 ])

Or even higher dimensional:

In [96]:
D = np.random.randn(3, 4, 5, 2, 5)

In [97]:
D.ndim

5

In [98]:
D.shape

(3, 4, 5, 2, 5)

Of course, most of the time we will be working with 1D (Vectors) and 2D (Matrices).

#### Summary of numpy
* `numpy.array` behaves like matlab vectors where basic mathematical operations is extendible to arrays.
* For matrix multiplication use `np.dot()`.
* `np.linalg.norm()` linear algebra submodule for advance linear algebraic equations.
* To solve $A \times x = b$, use `np.solve(A, b)`.
* One dimensional arrays (a) has shape like `(5, )`. You can reshape it to `a.reshape((5,1))` or use `a[:,none]`.
* Use `np.ndim` and `np.shape` to get the dimension and shape of the array. 