## Tensors

###  Introduction
In PyTorch, tensors are used to encode input, output and parameters of the model. Tensors are similar to ndarrays in numpy, except that they can gpus and other specialized hardware to acclerate computing.

In [1]:
import torch
import numpy as np

### **Initialization**

#### **1. Directly from Data**

In [2]:
data = [[1, 2], [3, 4]]
tensor_data = torch.tensor(data)
tensor_data_size = tensor_data.size()
print(f'tensor data = {tensor_data}, it has a size of {tensor_data_size}')

tensor data = tensor([[1, 2],
        [3, 4]]), it has a size of torch.Size([2, 2])


#### **2. From a NumPy array**

In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

#### **3. From another Tensor**

The new tensor retains the properties (shape, datatype) of the argument tensor, unless explicitely overridden

In [4]:
tensor_ones = torch.ones_like(tensor_data) # retains the properties of x_data
print(f'Ones Tensor: \n {tensor_ones} \n')
print(f'The datatype of ones tensor is {tensor_ones.dtype}')

tensor_rand = torch.rand_like(tensor_data, dtype=torch.float) # Overrides the datatype of x_data
print(f"Random Tensor: \n {tensor_rand} \n")
print(f"The datatype of tensor rand is  {tensor_rand.dtype}")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

The datatype of ones tensor is torch.int64
Random Tensor: 
 tensor([[0.9929, 0.9807],
        [0.9170, 0.1259]]) 

The datatype of tensor rand is  torch.float32


#### **4. With a Random or Constant values**

`shape` is a tuple of tensor dimensions. In the functions below, it determines the dimensionality o the output tensor.

In [5]:
shape = (2, 3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor} ")

Random Tensor: 
 tensor([[0.4223, 0.7349, 0.8150],
        [0.1617, 0.4098, 0.7279]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 


### **Tensor Attributes**

Tensor attributes describe tehir shape, datatype, and the device on which they are stored.

In [6]:
tensor_data = torch.rand(3, 4)

print(f"The shape of tensor is {tensor_data.shape}.")
print(f"The datatype of tensor is {tensor_data.dtype}.")
print(f"Tensor data is stored in  {tensor_data.device}.")

The shape of tensor is torch.Size([3, 4]).
The datatype of tensor is torch.float32.
Tensor data is stored in  cpu.


### **Tensor Operations**
Many operations that are part of numpy array are defined for tensors. Some of the most important operations and concepts are described below.

Tensors are suited for running the algorithm on GPUs. 

In [7]:
# We move our tensor to the GPU if available
device = torch.accelerator.current_accelerator().type if torch.accelerator.is_available() else 'cpu'
tensor_data = tensor_data.to(device)
print(f"Device tensor is stored on: {tensor_data.device}")

Device tensor is stored on: cuda:0


##### **Standard numpy-like indexing and slicing:**

In [9]:
tensor = torch.ones(4, 4)
tensor[:,1] = 0
print(tensor)
print(f"\n Tensor is stored in {tensor.device}")

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

 Tensor is stored in cpu


*Hence, data is usually stored in cpu, unless it is moved to gpu.*
**Joining tensors**: `torch.cat` , `torch.stack`

In [10]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


**Element-wise Multplication:** `tensor.mul(tensor)`, `tensor * tensor`


**Matrix Multiplication:** `tensor.matmul(tensor.T)`, `tensor @ tensor.T`

**In-place operations:** In-place operations in PyTorch are operations that directly modify the content of an existing tensor instead of creating a new tensor with the result, thereby improving memory efficiency. These operations have an `_` at the end of function name. `tensor.add_(5)`, ``tensor.copy(y)``, `tensor.t()`

> In-place operations can break the computational graph because they modify the tensor in-place, which may lead to incorrect gradient calculations.

### Bridging with NumPy
Tensors on the CPU and NumPy arrays can share their underlying memory locations, and changing one will change the other

#### Tensor to NumPy array

In [11]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


A change in the tensor reflects in the NumPy array.

In [12]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


#### NumPy array to Tensor

In [13]:
n = np.ones(5)
t =torch.from_numpy(n)


Changes in the NumPy array reflects in the tensor.

In [14]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
