## Tensors

###  Introduction
In PyTorch, tensors are used to encode input, output and parameters of the model. Tensors are similar to ndarrays in numpy, except that they can gpus and other specialized hardware to acclerate computing.

In [2]:
import torch
import numpy as np

### **Initialization**

#### **1. Directly from Data**

In [14]:
data = [[1, 2], [3, 4]]
tensor_data = torch.tensor(data)
tensor_data_size = tensor_data.size()
print(f'tensor data = {tensor_data}, it has a size of {tensor_data_size}')

tensor data = tensor([[1, 2],
        [3, 4]]), it has a size of torch.Size([2, 2])


#### **2. From a NumPy array**

In [15]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

#### **3. From another Tensor**

The new tensor retains the properties (shape, datatype) of the argument tensor, unless explicitely overridden

In [16]:
tensor_ones = torch.ones_like(tensor_data) # retains the properties of x_data
print(f'Ones Tensor: \n {tensor_ones} \n')
print(f'The datatype of ones tensor is {tensor_ones.dtype}')

tensor_rand = torch.rand_like(tensor_data, dtype=torch.float) # Overrides the datatype of x_data
print(f"Random Tensor: \n {tensor_rand} \n")
print(f"The datatype of tensor rand is  {tensor_rand.dtype}")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

The datatype of ones tensor is torch.int64
Random Tensor: 
 tensor([[0.3439, 0.7970],
        [0.3474, 0.1898]]) 

The datatype of tensor rand is  torch.float32


#### **4. With a Random or Constant values**

`shape` is a tuple of tensor dimensions. In the functions below, it determines the dimensionality o the output tensor.

In [17]:
shape = (2, 3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor} ")

Random Tensor: 
 tensor([[0.0031, 0.5717, 0.1510],
        [0.8588, 0.7212, 0.9426]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 


### **Tensor Attributes**

Tensor attributes describe tehir shape, datatype, and the device on which they are stored.

In [4]:
tensor_data = torch.rand(3, 4)

print(f"The shape of tensor is {tensor_data.shape}.")
print(f"The datatype of tensor is {tensor_data.dtype}.")
print(f"Tensor data is stored in  {tensor_data.device}.")

The shape of tensor is torch.Size([3, 4]).
The datatype of tensor is torch.float32.
Tensor data is stored in  cpu.


### **Tensor Operations**
Many operations that are part of numpy array are defined for tensors. Some of the most important operations and concepts are described below.

Tensors are suited for running the algorithm on GPUs. 

In [ ]:
# We move our tensor to the GPU if available
device = torch.accelerator.current_accelerator().type if torch.accelerator.is_available() else 'cpu'
tensor_data = tensor_data.to(device)
print(f"Device tensor is stored on: {tensor_data.device}")

Device tensor is stored on: cpu
